# Generated by Django 3.2 on 2021-04-26 15:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Answer title')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Correctness')),
                ('number_of_choice', models.IntegerField(default=0, verbose_name='The number of answer choice')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Question title')),
                ('response_time', models.TimeField(null=True, verbose_name='Question response time')),
                ('score', models.IntegerField(default=0, verbose_name='Answer score')),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.answer')),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=128, verbose_name='Poll title')),
                ('description', models.CharField(max_length=255, verbose_name='Poll description')),
                ('ready_at', models.DateTimeField(default=datetime.datetime(2021, 4, 26, 15, 53, 44, 725104), verbose_name='Poll ready date')),
                ('response_time', models.TimeField(null=True)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.question')),
            ],
        ),
    ]
