# Generated by Django 3.2 on 2021-04-26 15:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='ready_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 26, 15, 54, 55, 920133, tzinfo=utc), verbose_name='Poll ready date'),
        ),
    ]
