# Generated by Django 3.2 on 2021-04-26 15:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_poll_ready_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='ready_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Poll ready date'),
        ),
    ]
